<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalitySeeder extends Seeder
{
    public function run(): void
    {
        $municipalities = "INSERT INTO municipalities (muni_type_id,district_id,muni_code,muni_name,muni_name_en,created_at,updated_at) VALUES

            (3,1,'1','फुङ्लिङ नगरपालिका','Phungling Municipality',NULL,NULL),
            (4,1,'2','आठराई त्रिवेणी गाउँपालिका','Aathrai Tribeni Rural Municipality',NULL,NULL),
            (4,1,'3','सिदिङ्ग्वा गाउँपालिका','Sidingba Rural Municipality',NULL,NULL),
            (4,1,'4','फक्ताङलुङ गाउँपालिका','Phaktanglung Rural Municipality',NULL,NULL),
            (4,1,'5','मिक्वाखोला गाउँपालिका','Mikwakhola Rural Municipality',NULL,NULL),
            (4,1,'6','मेरिङ्देन गाउँपालिका','Meringden Rural Municipality',NULL,NULL),
            (4,1,'7','मैवाखोला गाउँपालिका','Maiwakhola Rural Municipality',NULL,NULL),
            (4,1,'8','पाथीभरा याङ्वरक गाउँपालिका','Pathivara Yangwarak Rural Municipality',NULL,NULL),
            (4,1,'9','सिरिजङ्गा गाउँपालिका','Sirijangha Rural Municipality',NULL,NULL),
            (3,2,'10','फिदिम नगरपालिका','Phidim Municipality',NULL,NULL),
            (4,2,'11','फालेलुङ गाउँपालिका','Falelung Rural Municipality',NULL,NULL),
            (4,2,'12','फाल्गुनन्द गाउँपालिका','Falgunanda Rural Municipality',NULL,NULL),
            (4,2,'13','हिलिहाङ गाउँपालिका','Hilihang Rural Municipality',NULL,NULL),
            (4,2,'14','कुम्मायक गाउँपालिका','Kummayak Rural Municipality',NULL,NULL),
            (4,2,'15','मिक्लाजुङ्ग गाउँपालिका',	'Miklajung Rural Municipality',NULL,NULL),
            (4,2,'16','तुम्वेहा गाउँपालिका','Tumbewa Rural Municipality',NULL,NULL),
            (4,2,'17','याङ्वरक गाउँपालिका','Yangwarak Rural Municipality',NULL,NULL),
            (3,3,'18','इलाम नगरपालिका','Illam Municipality',NULL,NULL),
            (3,3,'19','देउमाई नगरपालिका','Deumai Municipality',NULL,NULL),
            (3,3,'20','माई नगरपालिका','Mai Municipality',NULL,NULL),
            (3,3,'21','सूर्योदय नगरपालिका','Suryodaya Municipality',NULL,NULL),
            (4,3,'22','फाकफोकथुम गाउँपालिका ','Fakphokthum Rural Municipality',NULL,NULL),
            (4,3,'23','चुलाचुली गाउँपालिका','Chulachuli Rural Municipality',NULL,NULL),
            (4,3,'24','माईजोगमाई गाउँपालिका','Maijogmai Rural Municipality',NULL,NULL),
            (4,3,'25','माङ्सेबुङ गाउँपालिका','Mangsebung Rural Municipality',NULL,NULL),
            (4,3,'26','रोङ गाउँपालिका','NRong Rural MunicipalityULL',NULL,NULL),
            (4,3,'27','सन्दकपुर गाउँपालिका','Sandakpur Rural Municipality',NULL,NULL),
            (3,4,'28','मेचीनगर नगरपालिका','Mechinagar Municipality',NULL,NULL),
            (3,4,'29','दमक नगरपालिका','Damak Municipality',NULL,NULL),
            (3,4,'30','कन्काई नगरपालिका','Kankai Municipality',NULL,NULL),
            (3,4,'31','भद्रपुर नगरपालिका',	'Bhadrapur Municipality',NULL,NULL),
            (3,4,'32','अर्जुनधारा नगरपालिका','Arjundhara Municipality',NULL,NULL),
            (3,4,'33','शिवसताक्षी नगरपालिका ','Shivasataxi Municipality',NULL,NULL),
            (3,4,'34','गौरादह नगरपालिका','Gauradhaha Municipality',NULL,NULL),
            (3,4,'35','विर्तामोड नगरपालिका','Birtamod Municipality',NULL,NULL),
            (4,4,'36','कमल गाउँपालिका',	'Kamal Rural Municipality',NULL,NULL),
            (4,4,'37','गौरीगञ्ज गाउँपालिका','Gauriganj Rural Municipality',NULL,NULL),
            (4,4,'38','बाह्रदशी गाउँपालिका','Barhadashi Rural Municipality',NULL,NULL),
            (4,4,'39','झापा गाउँपालिका','Jhapa Rural Municipality',NULL,NULL),
            (4,4,'40','बुद्धशान्ती गाउँपालिका','Buddhashanti Rural Municipality',NULL,NULL),
            (4,4,'41','हल्दीवारी गाउँपालिका','Haldibari Rural Municipality',NULL,NULL),
            (4,4,'42','कचनकवल गाउँपालिका','Kachankawal Rural Municipality',NULL,NULL),
            (1,5,'43','विराटनगर महानगरपालिका','Biratnagar Metropolitian City',NULL,NULL),
            (3,5,'44','बेलबारी नगरपालिका','Belbari Municipality',NULL,NULL),
            (3,5,'45','लेटाङ्ग नगरपालिका','Letang Municipality',NULL,NULL),
            (3,5,'46','पथरी शनिश्चरे नगरपालिका','Patahrishanishchare Municipality',NULL,NULL),
            (3,5,'47','रङ्गेली नगरपालिका','Rangeli Municipality',NULL,NULL),
            (3,5,'48','रतुवामाई नगरपालिका','Ratuwamai Municipality',NULL,NULL),
            (3,5,'49','सुनवर्षी नगरपालिका','Sunwarshi Municipality',NULL,NULL),
            (3,5,'50','उर्लाबारी नगरपालिका','Uralabari Municipality',NULL,NULL),
            (3,5,'51','सुन्दरहरैंचा नगरपालिका','Sundarharaicha Municipality',NULL,NULL),
            (4,5,'52','बुढीगङ्गा गाउँपालिका','Budhiganga Rural Municipality',NULL,NULL),
            (4,5,'53','धनपालथान गाउँपालिका','Dhanpalthan Rural Municipality',NULL,NULL),
            (4,5,'54','ग्रामथान गाउँपालिका','Gramthan Rural Municipality',NULL,NULL),
            (4,5,'55','जहदा गाउँपालिका','Jahada Rural Municipality',NULL,NULL),
            (4,5,'56','कानेपोखरी गाउँपालिका','Kanepokhari Rural Municipality',NULL,NULL),
            (4,5,'57','कटहरी गाउँपालिका','Katahari Rural Municipality',NULL,NULL),
            (4,5,'58','केराबारी गाउँपालिका','Kerabari Rural Municipality',NULL,NULL),
            (4,5,'59','मिक्लाजुङ्ग गाउँपालिका','Miklajung Rural Municipality',NULL,NULL),
            (2,6,'60','ईटहरी उपमहानगरपालिका','Itahari Sub-Metropolitian City',NULL,NULL),
            (2,6,'61','धरान उपमहानगरपालिका','Dharan Sub-Metropolitian City',NULL,NULL),
            (3,6,'62','ईनरुवा नगरपालिका','Inaruwa Municipality',NULL,NULL),
            (3,6,'63','दुहवी नगरपालिका','Duhabi Municipality',NULL,NULL),
            (3,6,'64','रामधुनी नगरपालिका','Ramdhuni Municipality',NULL,NULL),
            (3,6,'65','बराहक्षेत्र नगरपालिका','Barahchhetra Municipality',NULL,NULL),
            (4,6,'66','देवानगञ्ज गाउँपालिका','Dewanganj Rural Municipality',NULL,NULL),
            (4,6,'67','कोशी गाउँपालिका','Koshi Rural Municipality',NULL,NULL),
            (4,6,'68','गढी गाउँपालिका','Gadhi Rural Municipality',NULL,NULL),
            (4,6,'69','बर्जु गाउँपालिका','Barju Rural Municipality',NULL,NULL),
            (4,6,'70','भोक्राहा गाउँपालिका','Bhokraha Narsing Rural Municipality',NULL,NULL),
            (4,6,'71','हरिनगर गाउँपालिका','Harinagar Rural Municipality',NULL,NULL),
            (3,7,'72','पाख्रीबास नगरपालिका','Pakhribas Municipality',NULL,NULL),
            (3,7,'73','धनकुटा नगरपालिका','Dhankuta Municipality',NULL,NULL),
            (3,7,'74','महालक्ष्मी नगरपालिका','Mahalaxmi Municipality',NULL,NULL),
            (4,7,'75','साँगुरीगढी गाउँपालिका','Sangurigadhi Rural Municipality',NULL,NULL),
            (4,7,'76','खाल्सा छिन्ताङ्ग शहीदभूमि गाउँपालिका','Shahidbhumi Rural Municipality',NULL,NULL),
            (4,7,'77','छथर जोरपाटी गाउँपालिका','Chhathar Jorpati Rural Municipality',NULL,NULL),
            (4,7,'78','चौविसे गाउँपालिका','Chaubise Rural Municipality',NULL,NULL),
            (3,8,'79','म्याङ्लुङ्ग नगरपालिका','Myanglung Municipality',NULL,NULL),
            (3,8,'80','लालीगुराँस नगरपालिका','Laligurans Municipality',NULL,NULL),
            (4,8,'81','आठराई गाउँपालिका','Aathrai Rural Municipality',NULL,NULL),
            (4,8,'82','छथर गाउँपालिका','Chhathar Rural Municipality',NULL,NULL),
            (4,8,'83','फेदाप गाउँपालिका','Phedap Rural Municipality',NULL,NULL),
            (4,8,'84','मेन्छयायेम गाउँपालिका','Menchayam Rural Municipality',NULL,NULL),
            (3,9,'85','चैनपुर नगरपालिका','Chainpur Municipality',NULL,NULL),
            (3,9,'86','धर्मदेवी नगरपालिका','Dharmadevi Municipality',NULL,NULL),
            (3,9,'87','खाँदबारी नगरपालिका','Khandbari Municipality',NULL,NULL),
            (3,9,'88','मादी नगरपालिका','Madi Municipality',NULL,NULL),
            (3,9,'89','पाँचखपन नगरपालिका','Panchakhapan Municipality',NULL,NULL),
            (4,9,'90','भोटखोला गाउँपालिका','Bhotkhola Rural Municipality',NULL,NULL),
            (4,9,'91','चिचिला गाउँपालिका','Chichila Rural Municipality',NULL,NULL),
            (4,9,'92','मकालु गाउँपालिका','Makalu Rural Municipality',NULL,NULL),
            (4,9,'93','सभापोखरी गाउँपालिका','Sabhapokhari Rural Municipality',NULL,NULL),
            (4,9,'94','सिलिचोङ्ग गाउँपालिका','Silichong Rural Municipality',NULL,NULL),
            (3,10,'95','भोजपुर नगरपालिका','Bhojpur Municipality',NULL,NULL),
            (3,10,'96','षडानन्द नगरपालिका','Shadananda Municipality',NULL,NULL),
            (4,10,'97','ट्याम्के मैयुम गाउँपालिका','Temkemaiyung Rural Municipality',NULL,NULL),
            (4,10,'98','रामप्रसादराई गाउँपालिका','Ramprasad Rai Rural Municipality',NULL,NULL),
            (4,10,'99','अरुण गाउँपालिका','Arun Rural Municipality',NULL,NULL),
            (4,10,'100','पौवादुम्मा गाउँपालिका','Pauwadungma Rural Municipality',NULL,NULL),
            (4,10,'101','साल्पा सिलिसो गाउँपालिका','Salpasilichho Rural Municipality',NULL,NULL),
            (4,10,'102','आम्चोक गाउँपालिका','Aamchowk Rural Municipality',NULL,NULL),
            (4,10,'103','हतुवागढी गाउँपालिका','Hatuwagadhi Rural Municipality',NULL,NULL),
            (3,11,'104','सोलु दुधकुण्ड नगरपालिका','Solududhakunda Municipality',NULL,NULL),
            (4,11,'105','दुधकोशी गाउँपालिका','Maapya Dudhkoshi Rural Municipality',NULL,NULL),
            (4,11,'106','खुम्बु पासाङ्गल्हामु गाउँपालिका','Khumbupasanglahmu Rural Municipality',NULL,NULL),
            (4,11,'107','दुधकौशीका गाउँपालिका','Thulung Dudhkoshi Rural Municipality',NULL,NULL),
            (4,11,'108','नेचा सल्यान गाउँपालिका','Nechasalyan Rural Municipality',NULL,NULL),
            (4,11,'109','महाकुलुङ्ग गाउँपालिका','Mahakulung Rural Municipality',NULL,NULL),
            (4,11,'110','लिखुपिके गाउँपालिका','Likhupike Rural Municipality',NULL,NULL),
            (4,11,'111','सोपाङ्ग गाउँपालिका','Sotang Rural Municipality',NULL,NULL),
            (3,12,'112','सिद्धिचरण नगरपालिका','Siddhicharan Municipality',NULL,NULL),
            (4,12,'113','खिजिदेम्बा गाउँपालिका','Khijidemba Rural Municipality',NULL,NULL),
            (4,12,'114','चम्पादेवी गाउँपालिका','Champadevi Rural Municipality',NULL,NULL),
            (4,12,'115','चिशंखुगढी गाउँपालिका','Chisankhugadhi Rural Municipality',NULL,NULL),
            (4,12,'116','मानेभञ्ज्याङ्ग गाउँपालिका','Manebhanjyang Rural Municipality',NULL,NULL),
            (4,12,'117','मोलुङ्ग गाउँपालिका','Molung Rural Municipality',NULL,NULL),
            (4,12,'118','लिखु गाउँपालिका','Likhu Rural Municipality',NULL,NULL),
            (4,12,'119','सुनकोशी गाउँपालिका','Sunkoshi Rural Municipality',NULL,NULL),
            (3,13,'120','हलेसी तुवाचुङ्ग नगरपालिका','Halesi Tuwachung Municipality',NULL,NULL),
            (3,13,'121','दिक्तेल रुपाकोट मझुवागढी नगरपालिका','Diktel Rupakot Majhuwagadhi Municipality',NULL,NULL),
            (4,13,'122','ऐसेलुखर्क गाउँपालिका','Ainselukhark Rural Municipality',NULL,NULL),
            (4,13,'123','रवा बेसी गाउँपालिका','Rawabesi Rural Municipality',NULL,NULL),
            (4,13,'124','जन्तेढुङ्गा गाउँपालिका','Jantedhunga Rural Municipality',NULL,NULL),
            (4,13,'125','खोटेहाङ्ग गाउँपालिका','Khotehang Rural Municipality',NULL,NULL),
            (4,13,'126','केपिलासगढी गाउँपालिका','Kepilasagadhi Rural Municipality',NULL,NULL),
            (4,13,'127','दिप्रुङ्ग गाउँपालिका','Diprung Chuichumma Rural Municipality',NULL,NULL),
            (4,13,'128','साकेला गाउँपालिका','Sakela Rural Municipality',NULL,NULL),
            (4,13,'129','बराहपोखरी गाउँपालिका','Barahapokhari Rural Municipality',NULL,NULL),
            (3,14,'130','कटारी नगरपालिका','Katari Municipality',NULL,NULL),
            (3,14,'131','चौदण्डीगढी नगरपालिका','Chaudandigadhi Municipality',NULL,NULL),
            (3,14,'132','त्रियुगा नगरपालिका','Triyuga Municipality',NULL,NULL),
            (3,14,'133','बेलका नगरपालिका','Belaka Municipality',NULL,NULL),
            (4,14,'134','उदयपुरगढी गाउँपालिका','Udayapurgadhi Rural Municipality',NULL,NULL),
            (4,14,'135','ताप्ली गाउँपालिका','Tapli Rural Municipality',NULL,NULL),
            (4,14,'136','रौताहामाई गाउँपालिका','Rautamai Rural Municipality',NULL,NULL),
            (4,14,'137','लिम्चुङबुङ गाउँपालिका','Limchungbung Rural Municipality',NULL,NULL),
            (3,15,'138','राजविराज नगरपालिका','Rajbiraj Municipality',NULL,NULL),
            (3,15,'139','कञ्चनरुप नगरपालिका','Kanchanrup Municipality',NULL,NULL),
            (3,15,'140','डाक्नेश्वरी नगरपालिका','Dakneshwori Municipality',NULL,NULL),
            (3,15,'141','बोदेबरसाईन नगरपालिका','Bode Barsain Municipality',NULL,NULL),
            (3,15,'142','खडक नगरपालिका','Khadak Municipality',NULL,NULL),
            (3,15,'143','शम्भुनाथ नगरपालिका','Shambhunath Municipality',NULL,NULL),
            (3,15,'144','सुरुङ्गा नगरपालिका','Surunga Municipality',NULL,NULL),
            (3,15,'145','हनुमाननगर कङ्कालिनी नगरपालिका','Hanumannagar Kankalini Municipality',NULL,NULL),
            (3,15,'146','सप्तकोशी नगरपालिका','Saptakoshi Rural Municipality',NULL,NULL),
            (4,15,'147','अग्नीसाइर कृष्णासवरन गाउँपालिका','Agnisair Krishna Savaran Rural Municipality',NULL,NULL),
            (4,15,'148','छिन्नमस्ता गाउँपालिका','Chhinnamasta Rural Municipality',NULL,NULL),
            (4,15,'149','महादेवा गाउँपालिका','Mahadeva Rural Municipality',NULL,NULL),
            (4,15,'150','तिरहुत गाउँपालिका','Tirahut Rural Municipality',NULL,NULL),
            (4,15,'151','तिलाठी कोइलाडी गाउँपालिका','Tilathi Koiladi Rural Municipality',NULL,NULL),
            (4,15,'152','रुपनी गाउँपालिका','Rupani Rural Municipality',NULL,NULL),
            (4,15,'153','राजगढ़ गाउँपालिका','Rajgadh Rural Municipality',NULL,NULL),
            (4,15,'154','विष्णुपुर गाउँपालिका','Bishnupur Rural Municipality',NULL,NULL),
            (4,15,'155','बलान-विहुल गाउँपालिका','Balan Bihul Rural Municipality',NULL,NULL),
            (3,16,'156','लहान नगरपालिका','Lahan Municipality',NULL,NULL),
            (3,16,'157','धनगढीमाई नगरपालिका','Dhangadhimai Municipality',NULL,NULL),
            (3,16,'158','सिरहा नगरपालिका','Siraha Municipality',NULL,NULL),
            (3,16,'159','गोलबजार नगरपालिका','Golbazar Municipality',NULL,NULL),
            (3,16,'160','मिर्चैया नगरपालिका','Mirchaiya Municipality',NULL,NULL),
            (3,16,'161','कल्याणपुर नगरपालिका','Kalyanpur Municipality',NULL,NULL),
            (3,16,'162','कर्जन्हा नगरपालिका','Karjanha Municipality',NULL,NULL),
            (3,16,'163','सुखीपुर नगरपालिका','Sukhipur Municipality',NULL,NULL),
            (4,16,'164','भगवानपुर गाउँपालिका','Bhagawanpur Rural Municipality',NULL,NULL),
            (4,16,'165','औरही गाउँपालिका','Aurahi Rural Municipality',NULL,NULL),
            (4,16,'166','विष्णुपुर गाउँपालिका','Bishnupur Rural Municipality',NULL,NULL),
            (4,16,'167','बरियारपट्टी गाउँपालिका','Bariyarpatti Rural Municipality',NULL,NULL),
            (4,16,'168','लक्ष्मीपुर पतारी गाउँपालिका','Laxmipur Patari Rural Municipality',NULL,NULL),
            (4,16,'169','नरहा गाउँपालिका','Naraha Rural Municipality',NULL,NULL),
            (4,16,'170','सखुवानान्करकट्टी गाउँपालिका','Sakhuwanankarkatti Rural Municipality',NULL,NULL),
            (4,16,'171','अर्नमा गाउँपालिका','Arnama Rural Municipality',NULL,NULL),
            (4,16,'172','नवराजपुर गाउँपालिका','Nawarajpur Rural Municipality',NULL,NULL),
            (2,17,'173','जनकपुरधाम उपमहानगरपालिका','Janakpurdham Sub-Metropolitian City',NULL,NULL),
            (3,17,'174','क्षिरेश्वरनाथ नगरपालिका','Chhireshwornath Municipality',NULL,NULL),
            (3,17,'175','गणेशमान चारनाथ नगरपालिका','Ganeshman Charnath Municipality',NULL,NULL),
            (3,17,'176','धनुषाधाम नगरपालिका','Dhanusadham Municipality',NULL,NULL),
            (3,17,'177','कमला नगरपालिका','Kamala Municipality',NULL,NULL),
            (3,17,'178','नगराइन नगरपालिका','Nagarain Municipality',NULL,NULL),
            (3,17,'179','विदेह नगरपालिका','Bideha Municipality',NULL,NULL),
            (3,17,'180','मिथिला नगरपालिका','Mithila Municipality',NULL,NULL),
            (3,17,'181','मिथिला विहारी नगरपालिका','Mithila Bihari Municipality',NULL,NULL),
            (3,17,'182','शहीदनगर नगरपालिका ','Sahidnagar Municipality',NULL,NULL),
            (3,17,'183','सबैला नगरपालिका','Sabaila Municipality',NULL,NULL),
            (3,17,'184','हंसपुर नगरपालिका','Hansapur Municipality',NULL,NULL),
            (4,17,'185','औरही गाउँपालिका','Aaurahi Rural Municipality',NULL,NULL),
            (4,17,'186','जनकनन्दिनी गाउँपालिका','Janaknandani Rural Municipality',NULL,NULL),
            (4,17,'187','बटेश्वर गाउँपालिका','Bateshwor Rural Municipality',NULL,NULL),
            (4,17,'188','मुखियापट्टी मुसहरनिया गाउँपालिका','Mukhiyapatti Musarmiya Rural Municipality',NULL,NULL),
            (4,17,'189','लक्ष्मीनिया गाउँपालिका','Lakshminiya Rural Municipality',NULL,NULL),
            (4,17,'190','धनौजी गाउँपालिका','Dhanauji Rural Municipality',NULL,NULL),
            (3,18,'191','जलेश्वर नगरपालिका','Jaleswor Municipality',NULL,NULL),
            (3,18,'192','बर्दिबास नगरपालिका','Bardibas Municipality',NULL,NULL),
            (3,18,'193','गौशाला नगरपालिका','Gaushala Municipality',NULL,NULL),
            (3,18,'194','बलवा नगरपालिका','Balwa Municipality',NULL,NULL),
            (3,18,'195','लोहरपट्टी नगरपालिका','Loharpatti Municipality',NULL,NULL),
            (3,18,'196','मनरा सिसवा नगरपालिका','Manra Siswa Municipality',NULL,NULL),
            (3,18,'197','रामगोपालपुर नगरपालिका','Ramgopalpur Municipality',NULL,NULL),
            (3,18,'198','औरही नगरपालिका','Aurahi Municipality',NULL,NULL),
            (3,18,'199','भँगाहा नगरपालिका','Bhangaha Municipality',NULL,NULL),
            (3,18,'200','मटिहानी नगरपालिका','Matihani Municipality',NULL,NULL),
            (4,18,'201','सोनमा गाउँपालिका','Sonama Rural Municipality',NULL,NULL),
            (4,18,'202','सम्सी गाउँपालिका','Samsi Rural Municipality',NULL,NULL),
            (4,18,'203','महोत्तरी गाउँपालिका','Mahottari Rural Municipality',NULL,NULL),
            (4,18,'204','पिपरा गाउँपालिका','Pipra Rural Municipality',NULL,NULL),
            (4,18,'205','एकडारा गाउँपालिका','Ekdanra Rural Municipality',NULL,NULL),
            (3,19,'206','ईश्वरपुर नगरपालिका','Ishworpur Municipality',NULL,NULL),
            (3,19,'207','मलङ्गवा नगरपालिका','Malangawa Municipality',NULL,NULL),
            (3,19,'208','लालबन्दी नगरपालिका','Lalbandi Municipality',NULL,NULL),
            (3,19,'209','हरिपुर नगरपालिका','Haripur Municipality',NULL,NULL),
            (3,19,'210','हरिपुर्वा नगरपालिका','Haripurwa Municipality',NULL,NULL),
            (3,19,'211','हरिवन नगरपालिका','Hariwan Municipality',NULL,NULL),
            (3,19,'212','बरहथवा नगरपालिका','Barahathawa Municipality',NULL,NULL),
            (3,19,'213','बलरा नगरपालिका','Balara Municipality',NULL,NULL),
            (3,19,'214','गोडैटा नगरपालिका','Godaita Municipality',NULL,NULL),
            (3,19,'215','बागमती नगरपालिका','Bagmati Municipality',NULL,NULL),
            (3,19,'216','कबिलासी नगरपालिका','Kabilasi Municipality',NULL,NULL),
            (4,19,'217','चक्रघट्टा गाउँपालिका','Chakraghatta Rural Municipality',NULL,NULL),
            (4,19,'218','चन्द्रनगर गाउँपालिका','Chandranagar Rural Municipality',NULL,NULL),
            (4,19,'219','धनकौल गाउँपालिका','Dhankaul Rural Municipality',NULL,NULL),
            (4,19,'220','ब्रह्मपुरी गाउँपालिका','Bramhapuri Rural Municipality',NULL,NULL),
            (4,19,'221','रामनगर गाउँपालिका','Ramnagar Rural Municipality',NULL,NULL),
            (4,19,'222','विष्णु गाउँपालिका','Bishnu Rural Municipality',NULL,NULL),
            (4,19,'223','बसबरीया गाउँपालिका','Basbariya Rural Municipality',NULL,NULL),
            (4,19,'224','कौडेना गाउँपालिका','Kaudena Rural Municipality',NULL,NULL),
            (4,19,'225','पर्सा गाउँपालिका','Parsa Rural Municipality',NULL,NULL),
            (3,20,'226','कटहरीया नगरपालिका','Katahariya Municipality',NULL,NULL),
            (3,20,'227','मौलापुर नगरपालिका','Maulapur Municipality',NULL,NULL),
            (3,20,'228','माधवनारायण नगरपालिका','Madhav Narayan Municipality',NULL,NULL),
            (3,20,'229','गरुडा नगरपालिका','Garuda Municipality',NULL,NULL),
            (3,20,'230','गौर नगरपालिका','Gaur Municipality',NULL,NULL),
            (3,20,'231','गजुरा नगरपालिका','Gujara Municipality',NULL,NULL),
            (3,20,'232','ईशनाथ नगरपालिका','Ishanath Municipality',NULL,NULL),
            (3,20,'233','चन्द्रपुर नगरपालिका','Chandrapur Municipality',NULL,NULL),
            (3,20,'234','देवाही गोनाही नगरपालिका','Dewahhi Gonahi Municipality',NULL,NULL),
            (3,20,'235','वृन्दावन नगरपालिका','Brindaban Municipality',NULL,NULL),
            (3,20,'236','राजपुर नगरपालिका','Rajpur Municipality',NULL,NULL),
            (3,20,'237','राजदेवी नगरपालिका','Rajdevi Municipality',NULL,NULL),
            (3,20,'238','गढीमाई नगरपालिका','Gadhimai Municipality',NULL,NULL),
            (3,20,'239','फतुवा विजयपुर नगरपालिका','Phatuwa Bijayapur Municipality',NULL,NULL),
            (3,20,'240','बौधीमाई नगरपालिका','Baudhimai Municipality',NULL,NULL),
            (3,20,'241','परोहा नगरपालिका','Paroha Municipality',NULL,NULL),
            (4,20,'242','यमुनामाई गाउँपालिका','Yemunamai Rural Municipality',NULL,NULL),
            (4,20,'243','दुर्गाभगवती गाउँपालिका','Durga Bhagwati Rural Municipality',NULL,NULL),
            (2,21,'244','कलैया उपमहानगरपालिका','Kalaiya Sub-Metropolitian City',NULL,NULL),
            (2,21,'245','जितपुर-सिमरा उपमहानगरपालिका','Jitpur Simara Sub-Metropolitian City',NULL,NULL),
            (3,21,'246','कोल्हवी नगरपालिका','Kolhabi Municipality',NULL,NULL),
            (3,21,'247','निजगढ नगरपालिका','Nijgadh Municipality',NULL,NULL),
            (3,21,'248','महागढीमाई नगरपालिका','Mahagadhimai Municipality',NULL,NULL),
            (3,21,'249','सिम्रौनगढ नगरपालिका','Simraungadh Municipality',NULL,NULL),
            (3,21,'250','पचरौता नगरपालिका','Pacharauta Municipality',NULL,NULL),
            (4,21,'251','परवानीपुर गाउँपालिका','Parwanipur Rural Municipality',NULL,NULL),
            (4,21,'252','प्रसौनी गाउँपालिका','Prasauni Rural Municipality',NULL,NULL),
            (4,21,'253','फेटा गाउँपालिका','Pheta Rural Municipality',NULL,NULL),
            (4,21,'254','आदर्श कोटवाल गाउँपालिका','Adarshkotwal Rural Municipality',NULL,NULL),
            (4,21,'255','करैयामाई गाउँपालिका','Karaiyamai Rural Municipality',NULL,NULL),
            (4,21,'256','देवताल गाउँपालिका','Devtal Rural Municipality',NULL,NULL),
            (4,21,'257','बारागढी गाउँपालिका','Baragadhi Rural Municipality',NULL,NULL),
            (4,21,'258','सुवर्ण गाउँपालिका','Suwarna Rural Municipality',NULL,NULL),
            (4,21,'259','विश्रामपुर गाउँपालिका','Bishrampur Rural Municipality',NULL,NULL),
            (1,22,'260','वीरगञ्ज महानगरपालिका','Birgunj Metropolitan City',NULL,NULL),
            (3,22,'261','पोखरीया नगरपालिका','Pokhariya Municipality',NULL,NULL),
            (3,22,'262','बहुदरमाई नगरपालिका','Bahudaramai Municipality',NULL,NULL),
            (3,22,'263','पर्सागढी नगरपालिका','Parsagadhi Municipality',NULL,NULL),
            (4,22,'264','ठोरी गाउँपालिका','Thori Rural Municipality',NULL,NULL),
            (4,22,'265','जगरनाथपुर गाउँपालिका','Jagarnathpur Rural Municipality',NULL,NULL),
            (4,22,'266','धोबीनी गाउँपालिका','Dhobini Rural Municipality',NULL,NULL),
            (4,22,'267','छिपहरमाई गाउँपालिका','Chhipaharmai Rural Municipality',NULL,NULL),
            (4,22,'268','पकाहा मैनपुर गाउँपालिका','Pakahamainpur Rural Municipality',NULL,NULL),
            (4,22,'269','विन्दबासिनी गाउँपालिका','Bindabasini Rural Municipality',NULL,NULL),
            (4,22,'270','सखुवा प्रसौनी गाउँपालिका','SakhuwaPrasauni Rural Municipality',NULL,NULL),
            (4,22,'271','पटेर्वा सुगौली गाउँपालिका','Paterwasugauli Rural Municipality',NULL,NULL),
            (4,22,'272','कालिकामाई गाउँपालिका','Kalikamai Rural Municipality',NULL,NULL),
            (4,22,'273','जिराभवानी गाउँपालिका','Jirabhawani Rural Municipality',NULL,NULL),
            (3,23,'274','कमलामाई नगरपालिका','Kamalamai Municipality',NULL,NULL),
            (3,23,'275','दुधौली नगरपालिका','Dudhouli Municipality',NULL,NULL),
            (4,23,'276','गोलञ्जोर गाउँपालिका','Golanjor Rural Municipality',NULL,NULL),
            (4,23,'277','घ्याङ्लेख गाउँपालिका','Ghanglekh Rural Municipality',NULL,NULL),
            (4,23,'278','तीनपाटन गाउँपालिका','Tinpatan Rural Municipality',NULL,NULL),
            (4,23,'279','फिक्कल गाउँपालिका','Phikkal Rural Municipality',NULL,NULL),
            (4,23,'280','मरिण गाउँपालिका','Marin Rural Municipality',NULL,NULL),
            (4,23,'281','सुनकोशी गाउँपालिका','Sunkoshi Rural Municipality',NULL,NULL),
            (4,23,'282','हरिहरपुरगढी गाउँपालिका','Hariharpurgadhi Rural Municipality',NULL,NULL),
            (3,24,'283','मन्थली नगरपालिका','Manthali Municipality',NULL,NULL),
            (3,24,'284','रामेछाप नगरपालिका','Ramechhap Municipality',NULL,NULL),
            (4,24,'285','उमाकुण्ड गाउँपालिका','Umakunda Rural Municipality',NULL,NULL),
            (4,24,'286','खाँडादेवी गाउँपालिका','Khadadevi Rural Municipality',NULL,NULL),
            (4,24,'287','गोकुलगङ्गा गाउँपालिका','Gokulganga Rural Municipality',NULL,NULL),
            (4,24,'288','दोरम्भा गाउँपालिका','Doramba Rural Municipality',NULL,NULL),
            (4,24,'289','लिखु गाउँपालिका','Likhu Tamakoshi Rural Municipality',NULL,NULL),
            (4,24,'290','सुनापती गाउँपालिका','Sunapati Rural Municipality',NULL,NULL),
            (3,25,'291','जिरी नगरपालिका','Jiri Municipality',NULL,NULL),
            (3,25,'292','भिमेश्वर नगरपालिका','Bhimeshwor Municipality',NULL,NULL),
            (4,25,'293','कालिञ्चोक गाउँपालिका','Kalinchok Rural Municipality',NULL,NULL),
            (4,25,'294','गौरीशङ्कर गाउँपालिका','Gaurishankar Rural Municipality',NULL,NULL),
            (4,25,'295','तामाकोशी गाउँपालिका','Tamakoshi Rural Municipality',NULL,NULL),
            (4,25,'296','मेलुङ्ग गाउँपालिका','Melung Rural Municipality',NULL,NULL),
            (4,25,'297','विगु गाउँपालिका','Bigu Rural Municipality',NULL,NULL),
            (4,25,'298','बैतेश्वर गाउँपालिका','Baiteshwor Rural Municipality',NULL,NULL),
            (4,25,'299','शैलुङ्ग गाउँपालिका','Sailung Rural Municipality',NULL,NULL),
            (3,26,'300','चौतारा साँगाचोकगढी नगरपालिका','Chautara SangachokGadhi Municipality',NULL,NULL),
            (3,26,'301','बाह्रविसे नगरपालिका','Barhabise Municipality',NULL,NULL),
            (3,26,'302','मेलम्ची नगरपालिका','Melamchi Municipality',NULL,NULL),
            (4,26,'303','ईन्द्रावती गाउँपालिका','Indrawati Rural Municipality',NULL,NULL),
            (4,26,'304','जुगल गाउँपालिका','Jugal Rural Municipality',NULL,NULL),
            (4,26,'305','पाँचपोखरी थाङ्पाल गाउँपालिका','Panchpokhari Thangpal Rural Municipality',NULL,NULL),
            (4,26,'306','बलेफी गाउँपालिका','Balefi Rural Municipality',NULL,NULL),
            (4,26,'307','भोटेकोशी गाउँपालिका','Bhotekoshi Rural Municipality',NULL,NULL),
            (4,26,'308','लिसङ्खुपाखर गाउँपालिका','Lisangkhu Pakhar Rural Municipality',NULL,NULL),
            (4,26,'309','सुनकोशी गाउँपालिका','Sunkoshi Rural Municipality',NULL,NULL),
            (4,26,'310','हेलम्बु गाउँपालिका','Helambu Rural Municipality',NULL,NULL),
            (4,26,'311','त्रिपुरासुन्दरी गाउँपालिका','Tripurasundari Rural Municipality',NULL,NULL),
            (3,27,'312','धुलिखेल नगरपालिका','Dhulikhel Municipality',NULL,NULL),
            (3,27,'313','बनेपा नगरपालिका','Banepa Municipality',NULL,NULL),
            (3,27,'314','पनौती नगरपालिका','Panauti Municipality',NULL,NULL),
            (3,27,'315','पाँचखाल नगरपालिका','Panchkhal Municipality',NULL,NULL),
            (3,27,'316','नमोबुद्ध नगरपालिका','Namobuddha Municipality',NULL,NULL),
            (3,27,'317','मण्डनदेउपुर नगरपालिका','Mandandeupur Municipality',NULL,NULL),
            (4,27,'318','खानीखोला गाउँपालिका','Khanikhola Rural Municipality',NULL,NULL),
            (4,27,'319','चौंरीदेउराली गाउँपालिका','Chaurideurali Rural Municipality',NULL,NULL),
            (4,27,'320','तेमाल गाउँपालिका','Temal Rural Municipality',NULL,NULL),
            (4,27,'321','बेथानचोक गाउँपालिका','Bethanchowk Rural Municipality',NULL,NULL),
            (4,27,'322','भुम्लु गाउँपालिका','Bhumlu Rural Municipality',NULL,NULL),
            (4,27,'323','महाभारत गाउँपालिका','Mahabharat Rural Municipality',NULL,NULL),
            (4,27,'324','रोशी गाउँपालिका','Roshi Rural Municipality',NULL,NULL),
            (1,28,'325','ललितपुर महानगरपालिका','Lalitpur Metropolitan City',NULL,NULL),
            (3,28,'326','गोदावरी नगरपालिका','Godawari Municipality',NULL,NULL),
            (3,28,'327','महालक्ष्मी नगरपालिका','Mahalaxmi Municipality',NULL,NULL),
            (4,28,'328','कोञ्ज्योसोम गाउँपालिका','Konjyosom Rural Municipality',NULL,NULL),
            (4,28,'329','बागमती गाउँपालिका','Bagmati Rural Municipality',NULL,NULL),
            (4,28,'330','महाङ्काल गाउँपालिका','Mahankal Rural Municipality',NULL,NULL),
            (3,29,'331','चाँगुनारायण नगरपालिका','Changunarayan Municipality',NULL,NULL),
            (3,29,'332','भक्तपुर नगरपालिका','Bhaktapur Municipality',NULL,NULL),
            (3,29,'333','मध्यपुर थिमी नगरपालिका','Madhyapur Thimi Municipality',NULL,NULL),
            (3,29,'334','सूर्यविनायक नगरपालिका','Suryabinayak Municipality',NULL,NULL),
            (1,30,'335','काठमाण्डौं महानगरपालिका','Kathmandu Metropolitan City',NULL,NULL),
            (3,30,'336','कागेश्वरी मनोहरा नगरपालिका','Kageshwori Manahora Municipality',NULL,NULL),
            (3,30,'337','कीर्तिपुर नगरपालिका','Kirtipur Municipality',NULL,NULL),
            (3,30,'338','गोकर्णेश्वर नगरपालिका','Gokarneshwor Municipality',NULL,NULL),
            (3,30,'339','चन्द्रागिरी नगरपालिका','Chandragiri Municipality',NULL,NULL),
            (3,30,'340','टोखा नगरपालिका','Tokha Municipality',NULL,NULL),
            (3,30,'341','तारकेश्वर नगरपालिका','Tarakeshwor Municipality',NULL,NULL),
            (3,30,'342','दक्षिणकाली नगरपालिका','Dakshinkali Municipality',NULL,NULL),
            (3,30,'343','नागार्जुन नगरपालिका','Nagarjun Municipality',NULL,NULL),
            (3,30,'344','बुढानिलकण्ठ नगरपालिका','Budhanilakantha Municipality',NULL,NULL),
            (3,30,'345','शङ्करापुर नगरपालिका','Shankharapur Municipality',NULL,NULL),
            (3,31,'346','विदुर नगरपालिका','Bidur Municipality',NULL,NULL),
            (3,31,'347','बेलकोटगढी नगरपालिका','Belkotgadhi Municipality',NULL,NULL),
            (4,31,'348','मेघाङ्ग गाउँपालिका','Myagang Rural Municipality',NULL,NULL),
            (4,31,'349','ककनी गाउँपालिका','Kakani Rural Municipality',NULL,NULL),
            (4,31,'350','किस्पाङ्ग गाउँपालिका','Kispang Rural Municipality',NULL,NULL),
            (4,31,'351','तादी गाउँपालिका','Tadi Rural Municipality',NULL,NULL),
            (4,31,'352','तारकेश्वर गाउँपालिका','Tarkeshwar Rural Municipality',NULL,NULL),
            (4,31,'353','दुप्चेश्वर गाउँपालिका','Dupcheshwar Rural Municipality',NULL,NULL),
            (4,31,'354','पञ्चकन्या गाउँपालिका','Panchakanya Rural Municipality',NULL,NULL),
            (4,31,'355','लिखु गाउँपालिका','Likhu Rural Municipality',NULL,NULL),
            (4,31,'356','शिवपुरी गाउँपालिका','Shivapuri Rural Municipality',NULL,NULL),
            (4,31,'357','सूर्यगढी गाउँपालिका','Suryagadhi Rural Municipality',NULL,NULL),
            (4,32,'358','उत्तरगया गाउँपालिका','Uttargaya Rural Municipality',NULL,NULL),
            (4,32,'359','कालिका गाउँपालिका','Kalika Rural Municipality',NULL,NULL),
            (4,32,'360','गोसाईंकुण्ड गाउँपालिका','Gosaikunda Rural Municipality',NULL,NULL),
            (4,32,'361','नौकुण्ड गाउँपालिका','Naukunda Rural Municipality',NULL,NULL),
            (4,32,'362','आमाछोदिङमो गाउँपालिका','Aamachhodingmo Rural Municipality',NULL,NULL),
            (3,33,'363','धुनीवेंशी नगरपालिका','Dhunibesi Municipality',NULL,NULL),
            (3,33,'364','निलकण्ठ नगरपालिका','Nilakantha Municipality',NULL,NULL),
            (4,33,'365','खनीयाबास गाउँपालिका','Khaniyabash Rural Municipality',NULL,NULL),
            (4,33,'366','गजुरी गाउँपालिका','Gajuri Rural Municipality',NULL,NULL),
            (4,33,'367','गल्छी गाउँपालिका','Galchi Rural Municipality',NULL,NULL),
            (4,33,'368','गङ्गाजमुना गाउँपालिका','Gangajamuna Rural Municipality',NULL,NULL),
            (4,33,'369','ज्वालामूखि गाउँपालिका','Jwalamukhi Rural Municipality',NULL,NULL),
            (4,33,'370','थाक्रे गाउँपालिका','Thakre Rural Municipality',NULL,NULL),
            (4,33,'371','नेत्रावती गाउँपालिका','Netrawati Dabjong Rural Municipality',NULL,NULL),
            (4,33,'372','बेनीघाट रोराङ्ग गाउँपालिका','Benighat Rorang Rural Municipality',NULL,NULL),
            (4,33,'373','रुबीभ्याली गाउँपालिका','Rubi Valley Rural Municipality',NULL,NULL),
            (4,33,'374','सिद्धलेक गाउँपालिका','Siddhalek Rural Municipality',NULL,NULL),
            (4,33,'375','त्रिपुरासुन्दरी गाउँपालिका','Tripura Sundari Rural Municipality',NULL,NULL),
            (2,34,'376','हेटौंडा उपमहानगरपालिका','Hetauda Sub-Metropolitian City',NULL,NULL),
            (3,34,'377','थाहा नगरपालिका','Thaha Municipality',NULL,NULL),
            (4,34,'378','ईन्द्रसरोवर गाउँपालिका','Indrasarowar Rural Municipality',NULL,NULL),
            (4,34,'379','कैलाश गाउँपालिका','Kailash Rural Municipality',NULL,NULL),
            (4,34,'380','बकैया गाउँपालिका','Bakaiya Rural Municipality',NULL,NULL),
            (4,34,'381','बागमती गाउँपालिका','Bagmati Rural Municipality',NULL,NULL),
            (4,34,'382','भीमफेदी गाउँपालिका','Bhimphedi Rural Municipality	',NULL,NULL),
            (4,34,'383','मकवानपुरगढी गाउँपालिका','Makawanpurgadhi Rural Municipality',NULL,NULL),
            (4,34,'384','मनोहरी गाउँपालिका','	Manohari Rural Municipality',NULL,NULL),
            (4,34,'385','राक्सीराङ्ग गाउँपालिका','Raksirang Rural Municipality',NULL,NULL),
            (1,35,'386','भरतपुर महानगरपालिका','Bharatpur Metropolitian City',NULL,NULL),
            (3,35,'387','कालिका नगरपालिका','Kalika Municipality',NULL,NULL),
            (3,35,'388','खैरहनी नगरपालिका','Khairahani Municipality',NULL,NULL),
            (3,35,'389','माडी नगरपालिका','Madi Municipality',NULL,NULL),
            (3,35,'390','रत्ननगर नगरपालिका','Ratnanagar Municipality',NULL,NULL),
            (3,35,'391','राप्ती नगरपालिका','Rapti Municipality',NULL,NULL),
            (4,35,'392','ईच्छाकामना गाउँपालिका','Ichchhyakamana Rural Municipality',NULL,NULL),
            (3,36,'393','गोरखा नगरपालिका','Gorkha Municipality',NULL,NULL),
            (3,36,'394','पालुङ्गटार नगरपालिका','Palungtar Municipality',NULL,NULL),
            (4,36,'395','बारपाक सुलीकोट गाउँपालिका','Barpak Sulikot Rural Municipality',NULL,NULL),
            (4,36,'396','सिरानचोक गाउँपालिका','Siranchok Rural Municipality',NULL,NULL),
            (4,36,'397','अजिरकोट गाउँपालिका','Ajirkot Rural Municipality',NULL,NULL),
            (4,36,'398','आरुघाट गाउँपालिका','Aarughat Rural Municipality',NULL,NULL),
            (4,36,'399','गण्डकी गाउँपालिका','Gandaki Rural Municipality',NULL,NULL),
            (4,36,'400','चुमनुब्री गाउँपालिका','Chum Nubri Rural Municipality',NULL,NULL),
            (4,36,'401','धार्चे गाउँपालिका','Dharche Rural Municipality',NULL,NULL),
            (4,36,'402','भिमसेन गाउँपालिका','Bhimsenthapa Rural Municipality',NULL,NULL),
            (4,36,'403','शहीदलखन गाउँपालिका','Sahid Lakhan Rural Municipality',NULL,NULL),
            (3,37,'404','बेंशीसहर नगरपालिका','Besishahar Municipality',NULL,NULL),
            (3,37,'405','मध्यनेपाल नगरपालिका','MadhyaNepal Municipality',NULL,NULL),
            (3,37,'406','राईनास नगरपालिका','Rainas Municipality',NULL,NULL),
            (3,37,'407','सुन्दरवजार नगरपालिका','Sundarbazar Municipality',NULL,NULL),
            (4,37,'408','क्व्होलासोथार गाउँपालिका','Kwholasothar Rural Municipality',NULL,NULL),
            (4,37,'409','दुधपोखरी गाउँपालिका','Dudhpokhari Rural Municipality',NULL,NULL),
            (4,37,'410','दोर्दी गाउँपालिका','Dordi Rural Municipality',NULL,NULL),
            (4,37,'411','मर्स्याङ्गदी गाउँपालिका','Marsyangdi Rural Municipality',NULL,NULL),
            (3,38,'412','कावासोती नगरपालिका','Kawasoti Municipality',NULL,NULL),
            (3,38,'413','गैंडाकोट नगरपालिका','Gaidakot Municipality',NULL,NULL),
            (3,38,'414','देवचुली नगरपालिका','Devchuli Municipality',NULL,NULL),
            (3,38,'415','मध्यविन्दु नगरपालिका','Madhyabindu Municipality',NULL,NULL),
            (4,38,'416','बुङ्दीकाली गाउँपालिका','Baudikali Rural Municipality',NULL,NULL),
            (4,38,'417','बुलिङ्टार गाउँपालिका','Bulingtar Rural Municipality',NULL,NULL),
            (4,38,'418','विनयीत्रिवेणी गाउँपालिका','Binayee Tribeni Rural Municipality',NULL,NULL),
            (4,38,'419','हुप्सेकोट गाउँपालिका','Hupsekot Rural Municipality',NULL,NULL),
            (3,39,'420','भानु नगरपालिका','Bhanu Municipality',NULL,NULL),
            (3,39,'421','भीमाद नगरपालिका','Bhimad Municipality',NULL,NULL),
            (3,39,'422','ब्यास नगरपालिका','Byas Municipality',NULL,NULL),
            (3,39,'423','शुक्लागण्डकी नगरपालिका','Shuklagandaki Municipality',NULL,NULL),
            (4,39,'424','आँबुखैरेनी गाउँपालिका','Anbukhaireni Rural Municipality',NULL,NULL),
            (4,39,'425','ऋषिङ्ग गाउँपालिका','Rhishing Rural Municipality',NULL,NULL),
            (4,39,'426','घिरिङ्ग गाउँपालिका','Ghiring Rural Municipality',NULL,NULL),
            (4,39,'427','देवघाट गाउँपालिका','Devghat Rural Municipality',NULL,NULL),
            (4,39,'428','म्याग्दे गाउँपालिका','Myagde Rural Municipality',NULL,NULL),
            (4,39,'429','बन्दिपुर गाउँपालिका','Bandipur Rural Municipality',NULL,NULL),
            (3,40,'430','गल्याङ्ग नगरपालिका','Galyang Municipality',NULL,NULL),
            (3,40,'431','चापाकोट नगरपालिका','Chapakot Municipality',NULL,NULL),
            (3,40,'432','पुतलीवजार नगरपालिका','Putalibazar Municipality',NULL,NULL),
            (3,40,'433','भीरकोट नगरपालिका','Bhirkot Municipality',NULL,NULL),
            (3,40,'434','वालिङ्ग नगरपालिका','Waling Municipality',NULL,NULL),
            (4,40,'435','अर्जुनचौपारी गाउँपालिका','Arjunchaupari Rural Municipality',NULL,NULL),
            (4,40,'436','आँधिखोला गाउँपालिका','Aandhikhola Rural Municipality',NULL,NULL),
            (4,40,'437','कालीगण्डकी गाउँपालिका','Kaligandagi Rural Municipality',NULL,NULL),
            (4,40,'438','फेदीखोला गाउँपालिका','Phedikhola Rural Municipality',NULL,NULL),
            (4,40,'439','विरुवा गाउँपालिका','Biruwa Rural Municipality',NULL,NULL),
            (4,40,'440','हरिनाश गाउँपालिका','Harinas Rural Municipality',NULL,NULL),
            (1,41,'441','पोखरा लेखनाथ महानगरपालिका','Pokhara Metropolitian City',NULL,NULL),
            (4,41,'442','अन्नपूर्ण गाउँपालिका','Annapurna Rural Municipality',NULL,NULL),
            (4,41,'443','माछापुच्छ्रे गाउँपालिका','Machhapuchchhre Rural Municipality',NULL,NULL),
            (4,41,'444','मादी गाउँपालिका','Madi Rural Municipality',NULL,NULL),
            (4,41,'445','रुपा गाउँपालिका','Rupa Rural Municipality',NULL,NULL),
            (4,42,'446','चामे गाउँपालिका','Chame Rural Municipality',NULL,NULL),
            (4,42,'447','नार्पा भूमि गाउँपालिका','Narpa Bhumi Rural Municipality',NULL,NULL),
            (4,42,'448','नासोँ गाउँपालिका','Narshon Rural Municipality',NULL,NULL),
            (4,42,'449','मनाङ ङिस्याङ गाउँपालिका','Manang Ingshyang Rural Municipality',NULL,NULL),
            (4,43,'450','घरपझोङ गाउँपालिका','Gharapjhong Rural Municipality',NULL,NULL),
            (4,43,'451','थासाङ गाउँपालिका','Thasang Rural Municipality',NULL,NULL),
            (4,43,'452','लो-घेकर दामोदरकुण्ड गाउँपालिका','Lo‑Ghekar Damodarkunda Rural Municipality ',NULL,NULL),
            (4,43,'453','लोमन्थाङ्ग गाउँपालिका','Lomanthang Rural Municipality',NULL,NULL),
            (4,43,'454','वारागुङ मुक्तिक्षेत्र गाउँपालिका','Varagung Muktichhetra Rural Municipality',NULL,NULL),
            (3,44,'455','बेनी नगरपालिका','Beni Municipality',NULL,NULL),
            (4,44,'456','अन्नपूर्ण गाउँपालिका','Annapurna Rural Municipality',NULL,NULL),
            (4,44,'457','धौलागिरी गाउँपालिका','Dhaulagiri Rural Municipality',NULL,NULL),
            (4,44,'458','मङ्गला गाउँपालिका','Mangala Rural Municipality',NULL,NULL),
            (4,44,'459','मालिका गाउँपालिका','Malika Rural Municipality',NULL,NULL),
            (4,44,'460','रघुगङ्गा गाउँपालिका','Raghuganga Rural Municipality',NULL,NULL),
            (3,45,'461','कुश्मा नगरपालिका','Kushma Municipality',NULL,NULL),
            (3,45,'462','फलेवास नगरपालिका','Phalebas Municipality',NULL,NULL),
            (4,45,'463','जलजला गाउँपालिका','Jaljala Rural Municipality',NULL,NULL),
            (4,45,'464','पैयुँ गाउँपालिका','Painyu Rural Municipality',NULL,NULL),
            (4,45,'465','महाशिला गाउँपालिका','Mahashila Rural Municipality',NULL,NULL),
            (4,45,'466','मोदी गाउँपालिका','Modi Rural Municipality',NULL,NULL),
            (4,45,'467','बिहादी गाउँपालिका','Bihadi Rural Municipality',NULL,NULL),
            (3,46,'468','बागलुङ्ग नगरपालिका','Baglung Municipality',NULL,NULL),
            (3,46,'469','गलकोट नगरपालिका','Galkot Municipality',NULL,NULL),
            (3,46,'470','जैमिनी नगरपालिका','Jaimuni Municipality',NULL,NULL),
            (3,46,'471','ढोरपाटन नगरपालिका','Dhorpatan Municipality',NULL,NULL),
            (4,46,'472','बरेङ्ग गाउँपालिका','Bareng Rural Municipality',NULL,NULL),
            (4,46,'473','कोठेखोला गाउँपालिका','Kathekhola Rural Municipality',NULL,NULL),
            (4,46,'474','तमानखोला गाउँपालिका','Taman Khola Rural Municipality',NULL,NULL),
            (4,46,'475','ताराखोला गाउँपालिका','Tara Khola Rural Municipality',NULL,NULL),
            (4,46,'476','निसीखोला गाउँपालिका','Nisikhola Rural Municipality',NULL,NULL),
            (4,46,'477','बढीगाड गाउँपालिका','Badigad Rural Municipality',NULL,NULL),
            (3,47,'478','मुसिकोट नगरपालिका','Musikot Municipality',NULL,NULL),
            (3,47,'479','रेसुङ्गा नगरपालिका','Resunga Municipality',NULL,NULL),
            (4,47,'480','ईश्मा गाउँपालिका','Isma Rural Municipality',NULL,NULL),
            (4,47,'481','कालीगण्डकी गाउँपालिका','Kaligandaki Rural Municipality',NULL,NULL),
            (4,47,'482','गुल्मीदरवार गाउँपालिका','Gulmidarbar Rural Municipality',NULL,NULL),
            (4,47,'483','सत्यवती गाउँपालिका','Satyawati Rural Municipality',NULL,NULL),
            (4,47,'484','चन्द्रकोट गाउँपालिका','Chandrakot Rural Municipality',NULL,NULL),
            (4,47,'485','रुरु गाउँपालिका','Ruru Rural Municipality',NULL,NULL),
            (4,47,'486','छत्रकोट गाउँपालिका','Chatrakot Rural Municipality',NULL,NULL),
            (4,47,'487','धुर्कोट गाउँपालिका','Dhurkot Rural Municipality',NULL,NULL),
            (4,47,'488','मदाने गाउँपालिका','Madane Rural Municipality',NULL,NULL),
            (4,47,'489','मालिका गाउँपालिका','Malika Rural Municipality',NULL,NULL),
            (3,48,'490','रामपुर नगरपालिका','Rampur Municipality',NULL,NULL),
            (3,48,'491','तान्सेन नगरपालिका','Tansen Municipality',NULL,NULL),
            (4,48,'492','निस्दी गाउँपालिका','Nisdi Rural Municipality',NULL,NULL),
            (4,48,'493','पूर्वखोला गाउँपालिका','Purbakhola Rural Municipality',NULL,NULL),
            (4,48,'494','रम्भा गाउँपालिका','Rambha Rural Municipality',NULL,NULL),
            (4,48,'495','मातागढी गाउँपालिका','Mathagadhi Rural Municipality',NULL,NULL),
            (4,48,'496','तिनाउ गाउँपालिका','Tinau Rural Municipality',NULL,NULL),
            (4,48,'497','बगनासकाली गाउँपालिका','Bagnaskali Rural Municipality',NULL,NULL),
            (4,48,'498','रिब्दिकोट गाउँपालिका','Ribdikot Rural Municipality',NULL,NULL),
            (4,48,'499','रैनादेवी छहरा गाउँपालिका','Rainadevi Chhahara Rural Municipality',NULL,NULL),
            (2,49,'500','बुटवल उपमहानगरपालिका','Butwal Sub-Metropolitian City',NULL,NULL),
            (3,49,'501','देवदह नगरपालिका','Devdaha Municipality',NULL,NULL),
            (3,49,'502','लुम्बिनी-साँस्कृतिक नगरपालिका','Lumbini Sanskritik Municipality',NULL,NULL),
            (3,49,'503','सैनामैना नगरपालिका','Sainamaina Municipality',NULL,NULL),
            (3,49,'504','सिद्धार्थनगर नगरपालिका','Siddharthanagar Municipality',NULL,NULL),
            (3,49,'505','तिलोत्तमा नगरपालिका','Tillotama Municipality',NULL,NULL),
            (4,49,'506','गैडहवा गाउँपालिका','Gaidahawa Rural Municipality',NULL,NULL),
            (4,49,'507','कञ्चन गाउँपालिका','Kanchan Rural Municipality',NULL,NULL),
            (4,49,'508','कोटहीमाई गाउँपालिका','Kotahimai Rural Municipality',NULL,NULL),
            (4,49,'509','मर्चवारी गाउँपालिका','Marchawari Rural Municipality',NULL,NULL),
            (4,49,'510','मायादेवी गाउँपालिका','Mayadevi Rural Municipality',NULL,NULL),
            (4,49,'511','ओमसतिया गाउँपालिका','Omsatiya Rural Municipality',NULL,NULL),
            (4,49,'512','रोहिणी गाउँपालिका','Rohini Rural Municipality',NULL,NULL),
            (4,49,'513','सम्मरीमाई गाउँपालिका','Sammarimai Rural Municipality',NULL,NULL),
            (4,49,'514','सियारी गाउँपालिका','Siyari Rural Municipality',NULL,NULL),
            (4,49,'515','सुद्धोदन गाउँपालिका','Sudhdhodhan Rural Municipality',NULL,NULL),
            (3,50,'516','कपिलवस्तु नगरपालिका','Kapilbastu Municipality',NULL,NULL),
            (3,50,'517','बुद्धभूमि नगरपालिका','Buddhabhumi Municipality',NULL,NULL),
            (3,50,'518','शिवराज नगरपालिका','Shivaraj Municipality',NULL,NULL),
            (3,50,'519','महाराजगञ्ज नगरपालिका','Maharajgunj Municipality',NULL,NULL),
            (3,50,'520','कृष्णनगर नगरपालिका','Krishnanagar Municipality',NULL,NULL),
            (3,50,'521','बाणगङ्गा नगरपालिका','Banganga Municipality',NULL,NULL),
            (4,50,'522','मायादेवी गाउँपालिका','Mayadevi Rural Municipality',NULL,NULL),
            (4,50,'523','यशोधरा गाउँपालिका','Yashodhara Rural Municipality',NULL,NULL),
            (4,50,'524','शुद्धोदन गाउँपालिका','Sudhdhodhan Rural Municipality',NULL,NULL),
            (4,50,'525','विजयनगर गाउँपालिका','Bijayanagar Rural Municipality',NULL,NULL),
            (3,51,'526','सन्धिखर्क नगरपालिका','Sandhikharka Municipality',NULL,NULL),
            (3,51,'527','शितगङ्गा नगरपालिका','Sitganga Municipality',NULL,NULL),
            (3,51,'528','भूमिकास्थान नगरपालिका','Bhumekasthan Municipality',NULL,NULL),
            (4,51,'529','छत्रदेव गाउँपालिका','Chhatradev Rural Municipality',NULL,NULL),
            (4,51,'530','पाणिनी गाउँपालिका','Panini Rural Municipality',NULL,NULL),
            (4,51,'531','मालारानी गाउँपालिका','Malarani Rural Municipality',NULL,NULL),
            (3,52,'532','प्युठान नगरपालिका ','Pyuthan Municipality',NULL,NULL),
            (3,52,'533','स्वर्गद्वारी नगरपालिका','Sworgadwary Municipality',NULL,NULL),
            (4,52,'534','गौमुखी गाउँपालिका','Gaumukhi Rural Municipality',NULL,NULL),
            (4,52,'535','माण्डवी गाउँपालिका','Mandavi Rural Municipality',NULL,NULL),
            (4,52,'536','सरुमारानी गाउँपालिका','Sarumarani Rural Municipality',NULL,NULL),
            (4,52,'537','मल्लरानी गाउँपालिका','Mallarani Rural Municipality',NULL,NULL),
            (4,52,'538','नौबहिनी गाउँपालिका','Naubahini Rural Municipality',NULL,NULL),
            (4,52,'539','झिमरुक गाउँपालिका','Jhimruk Rural Municipality',NULL,NULL),
            (4,52,'540','ऐरावती गाउँपालिका','Ayirabati Rural Municipality',NULL,NULL),
            (3,53,'541','रोल्पा नगरपालिका','Rolpa Municipality',NULL,NULL),
            (4,53,'542','त्रिवेणी गाउँपालिका','Tribeni Rural Municipality',NULL,NULL),
            (4,53,'543','परिवर्तन गाउँपालिका','Paribartan Rural Municipality',NULL,NULL),
            (4,53,'544','माडी गाउँपालिका','Madi Rural Municipality',NULL,NULL),
            (4,53,'545','रुन्टीगढी गाउँपालिका','Runtigadi Rural Municipality',NULL,NULL),
            (4,53,'546','लुङ्ग्री गाउँपालिका','Lungri Rural Municipality',NULL,NULL),
            (4,53,'547','गंगादेव गाउँपालिका','Ganagadev Rural Municipality',NULL,NULL),
            (4,53,'548','सुनछहरी गाउँपालिका','Sunchhahari Rural Municipality',NULL,NULL),
            (4,53,'549','सुनिलस्मृति गाउँपालिका','Sunil Smriti Rural Municipality',NULL,NULL),
            (4,53,'550','थवाङ्ग गाउँपालिका','Thawang Rural Municipality',NULL,NULL),
            (2,54,'551','तुल्सीपुर उपमहानगरपालिका','Tulsipur Sub-Metropolitian City',NULL,NULL),
            (2,54,'552','घोराही उपमहानगरपालिका','Ghorahi Sub-Metropolitian City',NULL,NULL),
            (3,54,'553','लमही नगरपालिका','Lamahi Municipality',NULL,NULL),
            (4,54,'554','बङ्गलाचुली गाउँपालिका','Banglachuli Rural Municipality',NULL,NULL),
            (4,54,'555','दङ्गीशरण गाउँपालिका','Dangisharan Rural Municipality',NULL,NULL),
            (4,54,'556','गढवा गाउँपालिका','Gadhawa Rural Municipality',NULL,NULL),
            (4,54,'557','राजपुर गाउँपालिका','Rajpur Rural Municipality',NULL,NULL),
            (4,54,'558','राप्ती गाउँपालिका','Rapti Rural Municipality',NULL,NULL),
            (4,54,'559','शान्तीनगर गाउँपालिका','Shantinagar Rural Municipality',NULL,NULL),
            (4,54,'560','बबई गाउँपालिका','Babai Rural Municipality',NULL,NULL),
            (2,55,'561','नेपालगञ्ज उपमहानगरपालिका','Nepalgunj Sub-Metropolitian City',NULL,NULL),
            (3,55,'562','कोहलपुर नगरपालिका','Kohalpur Municipality',NULL,NULL),
            (4,55,'563','नरैनापुर गाउँपालिका','Narainapur Rural Municipality',NULL,NULL),
            (4,55,'564','राप्तीसोनारी गाउँपालिका','Rapti Sonari Rural Municipality',NULL,NULL),
            (4,55,'565','बैजनाथ गाउँपालिका','Baijanath Rural Municipality',NULL,NULL),
            (4,55,'566','खजुरा गाउँपालिका','Khajura Rural Municipality',NULL,NULL),
            (4,55,'567','डुडुवा गाउँपालिका','Duduwa Rural Municipality',NULL,NULL),
            (4,55,'568','जानकी गाउँपालिका','Janki Rural Municipality',NULL,NULL),
            (3,56,'569','गुलरिया नगरपालिका','Gulariya Municipality',NULL,NULL),
            (3,56,'570','मधुवन नगरपालिका','Madhuwan Municipality',NULL,NULL),
            (3,56,'571','राजापुर नगरपालिका','Rajapur Municipality',NULL,NULL),
            (3,56,'572','ठाकुरबाबा नगरपालिका','Thakurbaba Municipality',NULL,NULL),
            (3,56,'573','बाँसगढी नगरपालिका','Bansagadhi Municipality',NULL,NULL),
            (3,56,'574','बारबर्दिया नगरपालिका','Barbardiya Municipality',NULL,NULL),
            (4,56,'575','बढैयाताल गाउँपालिका','Badhaiyatal Rural Municipality',NULL,NULL),
            (4,56,'576','गेरुवा गाउँपालिका','Geruwa Rural Municipality',NULL,NULL),
            (4,57,'577','पुथाउथरगङ्गा गाउँपालिका','Putha Uttarganga Rural Municipality',NULL,NULL),
            (4,57,'578','भूमे गाउँपालिका','Bhume Rural Municipality',NULL,NULL),
            (4,57,'579','सिस्ने गाउँपालिका','Sisne Rural Municipality',NULL,NULL),
            (3,58,'580','बर्दघाट नगरपालिका','Bardaghat Municipality',NULL,NULL),
            (3,58,'581','रामग्राम नगरपालिका','Ramgram Municipality',NULL,NULL),
            (3,58,'582','सुनवल नगरपालिका','Sunwal Municipality',NULL,NULL),
            (4,58,'583','सुस्ता गाउँपालिका','Susta Rural Municipality',NULL,NULL),
            (4,58,'584','पाल्हीनन्दन गाउँपालिका','Palhi Nandan Rural Municipality',NULL,NULL),
            (4,58,'585','प्रतापपुर गाउँपालिका','Pratappur Rural Municipality',NULL,NULL),
            (4,58,'586','सरावल गाउँपालिका','Sarawal Rural Municipality',NULL,NULL),
            (3,59,'587','मुसीकोट नगरपालिका','Musikot Municipality',NULL,NULL),
            (3,59,'588','चौरजहारी नगरपालिका','Chaurjahari Municipality',NULL,NULL),
            (3,59,'589','आठविसकोट नगरपालिका','Aathbiskot Municipality',NULL,NULL),
            (4,59,'590','बाफिकोट गाउँपालिका','Banfikot Rural Municipality',NULL,NULL),
            (4,59,'591','त्रिवेणी गाउँपालिका','Tribeni Rural Municipality',NULL,NULL),
            (4,59,'592','सानीभेरी गाउँपालिका','Sani Bheri Rural Municipality',NULL,NULL),
            (3,60,'593','शारदा नगरपालिका','Sharada Municipality',NULL,NULL),
            (3,60,'594','बाघचौर नगरपालिका','Bagchaur Municipality',NULL,NULL),
            (3,60,'595','बनगाड कुपिण्डे नगरपालिका','Bangad Kupinde Municipality',NULL,NULL),
            (4,60,'596','कालीमाटी गाउँपालिका','Kalimati Rural Municipality',NULL,NULL),
            (4,60,'597','त्रिवेणी गाउँपालिका','Tribeni Rural Municipality',NULL,NULL),
            (4,60,'598','कपुरकोट गाउँपालिका','Kapurkot Rural Municipality',NULL,NULL),
            (4,60,'599','छत्रेश्वरी गाउँपालिका','Chhatreshwori Rural Municipality',NULL,NULL),
            (4,60,'600','सिद्ध कुमाख गाउँपालिका','Siddha Kumakh Rural Municipality',NULL,NULL),
            (4,60,'601','कुमाख गाउँपालिका','Kumakh Rural Municipality',NULL,NULL),
            (4,60,'602','दार्मा गाउँपालिका','Darma Rural Municipality',NULL,NULL),
            (3,61,'603','वीरेन्द्रनगर नगरपालिका','Birendranagar Municipality',NULL,NULL),
            (3,61,'604','भेरीगङ्गा नगरपालिका','Bheriganga Municipality',NULL,NULL),
            (3,61,'605','गुर्भाकोट नगरपालिका','Gurbhakot Municipality',NULL,NULL),
            (3,61,'606','पञ्चपुरी नगरपालिका','Panchpuri Municipality',NULL,NULL),
            (3,61,'607','लेकवेंशी नगरपालिका','Lekbeshi Municipality',NULL,NULL),
            (4,61,'608','चौकुने गाउँपालिका','Chaukune Rural Municipality',NULL,NULL),
            (4,61,'609','बराहताल गाउँपालिका','Barahtal Rural Municipality',NULL,NULL),
            (4,61,'610','चिंगाड गाउँपालिका','Chingad Rural Municipality',NULL,NULL),
            (4,61,'611','सिम्ता गाउँपालिका','Simta Rural Municipality',NULL,NULL),
            (3,62,'612','नारायण नगरपालिका','Narayan Municipality',NULL,NULL),
            (3,62,'613','दुल्लु नगरपालिका','Dullu Municipality',NULL,NULL),
            (3,62,'614','चामुण्डा विन्द्रासैनी नगरपालिका','Chamunda Bindrasaini Municipality',NULL,NULL),
            (3,62,'615','आठविस नगरपालिका','Aathabis Municipality',NULL,NULL),
            (4,62,'616','भगवतीमाई गाउँपालिका','Bhagawatimai Rural Municipality',NULL,NULL),
            (4,62,'617','गुराँस गाउँपालिका','Gurans Rural Municipality',NULL,NULL),
            (4,62,'618','ढुङ्गेश्वर गाउँपालिका','Dungeshwor Rural Municipality',NULL,NULL),
            (4,62,'619','नौमुले गाउँपालिका','Naumule Rural Municipality',NULL,NULL),
            (4,62,'620','महाबु गाउँपालिका','Mahabu Rural Municipality',NULL,NULL),
            (4,62,'621','भैरवी गाउँपालिका','Bhairabi Rural Municipality',NULL,NULL),
            (4,62,'622','ठाँटीकाँध गाउँपालिका','Thantikandh Rural Municipality',NULL,NULL),
            (3,63,'623','भेरी नगरपालिका','Bheri Municipality',NULL,NULL),
            (3,63,'624','छेडागाड नगरपालिका','Chhedagad Municipality',NULL,NULL),
            (3,63,'625','नलगाड नगरपालिका','Nalagad Municipality',NULL,NULL),
            (4,63,'626','कुशे गाउँपालिका','Kuse Rural Municipality',NULL,NULL),
            (4,63,'627','जुनीचाँदे गाउँपालिका','Junichande Rural Municipality',NULL,NULL),
            (4,63,'628','बारेकोट गाउँपालिका','Barekot Rural Municipality',NULL,NULL),
            (4,63,'629','शिवालय गाउँपालिका','Shiwalaya Rural Municipality',NULL,NULL),
            (3,64,'630','ठूलीभेरी नगरपालिका','Thuli Bheri Municipality',NULL,NULL),
            (3,64,'631','त्रिपुरासुन्दरी नगरपालिका','Tripurasundari Municipality',NULL,NULL),
            (4,64,'632','डोल्पोबुद्ध गाउँपालिका','Dolpo Buddha Rural Municipality',NULL,NULL),
            (4,64,'633','शे-फोक्सुण्डो गाउँपालिका','Shey Phoksundo Rural Municipality',NULL,NULL),
            (4,64,'634','जगदुल्ला गाउँपालिका','Jagadulla Rural Municipality',NULL,NULL),
            (4,64,'635','मुड्केचुला गाउँपालिका','Mudkechula Rural Municipality',NULL,NULL),
            (4,64,'636','काईके गाउँपालिका','Kaike Rural Municipality',NULL,NULL),
            (4,64,'637','छार्का ताङ्सोङ्ग गाउँपालिका','Chharka Tangsong Rural Municipality',NULL,NULL),
            (3,65,'638','चन्दननाथ नगरपालिका','Chandannath Municipality',NULL,NULL),
            (4,65,'639','कनका सुन्दरी गाउँपालिका','Kanakasundari Rural Municipality',NULL,NULL),
            (4,65,'640','सिंजा गाउँपालिका','Sinja Rural Municipality',NULL,NULL),
            (4,65,'641','हिमा गाउँपालिका','Hima Rural Municipality',NULL,NULL),
            (4,65,'642','तिला गाउँपालिका','Tila Rural Municipality',NULL,NULL),
            (4,65,'643','गुठीचौर गाउँपालिका','Guthichaur Rural Municipality',NULL,NULL),
            (4,65,'644','तातोपानी गाउँपालिका','Tatopani Rural Municipality',NULL,NULL),
            (4,65,'645','पातारासी गाउँपालिका','Patrasi Rural Municipality',NULL,NULL),
            (3,66,'646','खाँडाचक्र नगरपालिका','Khandachakra Municipality',NULL,NULL),
            (3,66,'647','रासकोट नगरपालिका','Raskot Municipality',NULL,NULL),
            (3,66,'648','तिलागुफा नगरपालिका','Tilagufa Municipality',NULL,NULL),
            (4,66,'649','पचालझरना गाउँपालिका','Pachaljharana Rural Municipality',NULL,NULL),
            (4,66,'650','सान्नीत्रिवेणी गाउँपालिका','Sanni Tribeni Rural Municipality',NULL,NULL),
            (4,66,'651','नरहरीनाथ गाउँपालिका','Naraharinath Rural Municipality',NULL,NULL),
            (4,66,'652','शुभ कालीका गाउँपालिका','Shubha Kalika Rural Municipality',NULL,NULL),
            (4,66,'653','महाबै गाउँपालिका','Mahawai Rural Municipality',NULL,NULL),
            (4,66,'654','पलाता गाउँपालिका','Palata Rural Municipality',NULL,NULL),
            (3,67,'655','छायानाथ रारा नगरपालिका','Chhayanath Rara Municipality',NULL,NULL),
            (4,67,'656','मुगुम मकार्मारोंग गाउँपालिका','Mugum Karmarong Rural Municipality',NULL,NULL),
            (4,67,'657','सोरु गाउँपालिका','Soru Rural Municipality',NULL,NULL),
            (4,67,'658','खत्याड गाउँपालिका','Khatyad Rural Municipality',NULL,NULL),
            (4,68,'659','सिमकोट गाउँपालिका','Simkot Rural Municipality',NULL,NULL),
            (4,68,'660','नाम्खा गाउँपालिका','Namkha Rural Municipality',NULL,NULL),
            (4,68,'661','खार्पुनाथ गाउँपालिका','Kharpunath Rural Municipality',NULL,NULL),
            (4,68,'662','सर्केगाड गाउँपालिका','Sarkegad Rural Municipality',NULL,NULL),
            (4,68,'663','चङ्खेली गाउँपालिका','Chankheli Rural Municipality',NULL,NULL),
            (4,68,'664','अदानचुली गाउँपालिका','Adanchuli Rural Municipality',NULL,NULL),
            (4,68,'665','ताँजाकोट गाउँपालिका','Tanjakot Rural Municipality',NULL,NULL),
            (3,69,'666','बडीमालिका नगरपालिका','Badimalika Municipality',NULL,NULL),
            (3,69,'667','त्रिवेणी नगरपालिका','Tribeni Municipality',NULL,NULL),
            (3,69,'668','बुढीगङ्गा नगरपालिका','Budhiganga Municipality',NULL,NULL),
            (3,69,'669','बुढीनन्दा नगरपालिका','Budhinanda Municipality',NULL,NULL),
            (4,69,'670','गौमूल गाउँपालिका','Gaumul Rural Municipality',NULL,NULL),
            (4,69,'671','जगन्नाथ गाउँपालिका','Jagannath Rural Municipality',NULL,NULL),
            (4,69,'672','स्वामिकार्तिक गाउँपालिका','Swami Kartik Khaapar Rural Municipality',NULL,NULL),
            (4,69,'673','खप्तड छेडेदह गाउँपालिका','khaptad Chhededaha Rural Municipality',NULL,NULL),
            (4,69,'674','हिमाली गाउँपालिका','Himali Rural Municipality',NULL,NULL),
            (3,70,'675','जयपृथ्वी नगरपालिका','JayaPrithivi Municipality',NULL,NULL),
            (3,70,'676','बुङ्गल नगरपालिका','Bungal Municipality',NULL,NULL),
            (4,70,'677','तलकोट गाउँपालिका','Talkot Rural Municipality',NULL,NULL),
            (4,70,'678','मस्टा गाउँपालिका','Masta Rural Municipality',NULL,NULL),
            (4,70,'679','खप्तड छात्रा गाउँपालिका','Khaptadchhanna Rural Municipality',NULL,NULL),
            (4,70,'680','थलारा गाउँपालिका','Thalara Rural Municipality',NULL,NULL),
            (4,70,'681','विथ्थडचिर गाउँपालिका','Bitthadchir Rural Municipality',NULL,NULL),
            (4,70,'682','सुर्मा गाउँपालिका','Surma Rural Municipality',NULL,NULL),
            (4,70,'683','छब्बिसपाथीभेरा गाउँपालिका','Chabispathivera Rural Municipality',NULL,NULL),
            (4,70,'684','दुर्गाथली गाउँपालिका','Durgathali Rural Municipality',NULL,NULL),
            (4,70,'685','केदारस्यूँ गाउँपालिका','Kedarseu Rural Municipality',NULL,NULL),
            (4,70,'686','सइपाल गाउँपालिका','Saipal Rural Municipality',NULL,NULL),
            (3,71,'687','मङ्गलसेन नगरपालिका','Mangalsen Municipality',NULL,NULL),
            (3,71,'688','कमलवजार नगरपालिका','Kamalbazar Municipality',NULL,NULL),
            (3,71,'689','साँफेबगर नगरपालिका','Sanphebagar Municipality',NULL,NULL),
            (3,71,'690','पञ्चदेवल विनायक नगरपालिका','Panchadewal Binayak Municipality',NULL,NULL),
            (4,71,'691','चौरपाटी गाउँपालिका','Chaurpati Rural Municipality',NULL,NULL),
            (4,71,'692','मेल्लेख गाउँपालिका','Mellekh Rural Municipality',NULL,NULL),
            (4,71,'693','बाँन्नीगढी जयगढ गाउँपालिका','Bannigadhi Jayagadh Rural Municipality',NULL,NULL),
            (4,71,'694','रामारोसन गाउँपालिका','Ramaroshan Rural Municipality',NULL,NULL),
            (4,71,'695','ढकारी गाउँपालिका','Dhakari Rural Municipality',NULL,NULL),
            (4,71,'696','तुर्माखाँद गाउँपालिका','Turmakhad Rural Municipality',NULL,NULL),
            (3,72,'697','दिपायल सिलगढी नगरपालिका','Dipayal Silgadi Municipality',NULL,NULL),
            (3,72,'698','शिखर नगरपालिका','Shikhar Municipality',NULL,NULL),
            (4,72,'699','पूर्वीचौकी गाउँपालिका','Purbichauki Rural Municipality',NULL,NULL),
            (4,72,'700','बढीकेदार गाउँपालिका','Badikedar Rural Municipality',NULL,NULL),
            (4,72,'701','जोरायल गाउँपालिका','Jorayal Rural Municipality',NULL,NULL),
            (4,72,'702','सायल गाउँपालिका','Sayal Rural Municipality',NULL,NULL),
            (4,72,'703','आदर्श गाउँपालिका','Adharsha Rural Municipality',NULL,NULL),
            (4,72,'704','के.आई.सिङ्ग गाउँपालिका','K I Singh Rural Municipality',NULL,NULL),
            (4,72,'705','बोगटान गाउँपालिका','Bogtan Foodsil Rural Municipality',NULL,NULL),
            (2,73,'706','धनगढी उपमहानगरपालिका','Dhangadhi Sub-Metropolitian City',NULL,NULL),
            (3,73,'707','टिकापुर नगरपालिका','Tikapur Municipality',NULL,NULL),
            (3,73,'708','घोडाघोडी नगरपालिका','Ghodaghodi Municipality',NULL,NULL),
            (3,73,'709','लम्कीचुहा नगरपालिका','Lamkichuha Municipality',NULL,NULL),
            (3,73,'710','भजनी नगरपालिका','Bhajani Municipality',NULL,NULL),
            (3,73,'711','गोदावरी नगरपालिका','Godawari Municipality',NULL,NULL),
            (3,73,'712','गौरीगङ्गा नगरपालिका','Gauriganga Municipality',NULL,NULL),
            (4,73,'713','जानकी गाउँपालिका','Janaki Rural Municipality',NULL,NULL),
            (4,73,'714','बर्दगोरिया गाउँपालिका','Bardagoriya Rural Municipality',NULL,NULL),
            (4,73,'715','मोहन्याल गाउँपालिका','Mohanyal Rural Municipality',NULL,NULL),
            (4,73,'716','कैलारी गाउँपालिका','Kailari Rural Municipality',NULL,NULL),
            (4,73,'717','जोशीपुर गाउँपालिका','Joshipur Rural Municipality',NULL,NULL),
            (4,73,'718','चुरे गाउँपालिका','Chure Rural Municipality',NULL,NULL),
            (3,74,'719','भिमदत्त नगरपालिका','Bhimdatta Municipality',NULL,NULL),
            (3,74,'720','पुनर्वास नगरपालिका','Punarbas Municipality',NULL,NULL),
            (3,74,'721','बेदकोट नगरपालिका','Bedkot Municipality',NULL,NULL),
            (3,74,'722','महाकाली नगरपालिका','Mahakali Municipality',NULL,NULL),
            (3,74,'723','शुक्लाफाँटा नगरपालिका','Shuklaphanta Municipality',NULL,NULL),
            (3,74,'724','बेलौरी नगरपालिका','Belauri Municipality',NULL,NULL),
            (3,74,'725','कृष्णपुर नगरपालिका','Krishnapur Municipality',NULL,NULL),
            (4,74,'726','बेलडाँडी गाउँपालिका','Beldandi Rural Municipality',NULL,NULL),
            (4,74,'727','लालझाँडी गाउँपालिका','Laljhadi Rural Municipality',NULL,NULL),
            (3,75,'728','अमरगढी नगरपालिका','Amargadhi Municipality',NULL,NULL),
            (3,75,'729','परशुराम नगरपालिका','Parashuram Municipality',NULL,NULL),
            (4,75,'730','आलिताल गाउँपालिका','Alital Rural Municipality',NULL,NULL),
            (4,75,'731','भागेश्वर गाउँपालिका','Bhageshwar Rural Municipality',NULL,NULL),
            (4,75,'732','नवदुर्गा गाउँपालिका','Nawadurga Rural Municipality',NULL,NULL),
            (4,75,'733','अजयमेरु गाउँपालिका','Ajaymeru Rural Municipality',NULL,NULL),
            (4,75,'734','गन्यापधुरा गाउँपालिका','Ganayapdhura Rural Municipality',NULL,NULL),
            (3,76,'735','दशरथचन्द नगरपालिका','Dasharathchanda Municipality',NULL,NULL),
            (3,76,'736','पाटन नगरपालिका','Patan Municipality',NULL,NULL),
            (3,76,'737','मेलौली नगरपालिका','Melauli Municipality',NULL,NULL),
            (3,76,'738','पुचौडी नगरपालिका','Purchaudi Municipality',NULL,NULL),
            (4,76,'739','सुर्नया गाउँपालिका','Surnaya Rural Municipality',NULL,NULL),
            (4,76,'740','सिगास गाउँपालिका','Sigas Rural Municipality',NULL,NULL),
            (4,76,'741','शिवनाथ गाउँपालिका','Shivanath Rural Municipality',NULL,NULL),
            (4,76,'742','पञ्चेश्वर गाउँपालिका','Pancheshwar Rural Municipality',NULL,NULL),
            (4,76,'743','दगेडा केदार गाउँपालिका','Dogdakedar Rural Municipality',NULL,NULL),
            (4,76,'744','डिलासैनी गाउँपालिका','Dilasaini Rural Municipality',NULL,NULL),
            (3,77,'745','महाकाली नगरपालिका','Mahakali Municipality',NULL,NULL),
            (3,77,'746','शैलेश शिखर नगरपालिका','Shailyashikhar Municipality',NULL,NULL),
            (4,77,'747','मालिकार्जुन गाउँपालिका','Malikaarjun Rural Municipality',NULL,NULL),
            (4,77,'748','अपिहिमाल गाउँपालिका','Apihimal Rural Municipality',NULL,NULL),
            (4,77,'749','दुहुँ गाउँपालिका','Dunhu Rural Municipality',NULL,NULL),
            (4,77,'750','नौगाड गाउँपालिका','Naugad Rural Municipality',NULL,NULL),
            (4,77,'751','मार्मा गाउँपालिका','Marma Rural Municipality',NULL,NULL),
            (4,77,'752','लेकम गाउँपालिका','Lekam Rural Municipality',NULL,NULL),
            (4,77,'753','ब्यास गाउँपालिका','Byas Rural Municipality',NULL,NULL)
            ";
        DB::statement($municipalities);
    }
}
